### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by arxon31** [jfjallid/go-smb#10]
Question about smb package

How can I create new directory or make something like os.MkdirAll with your library?

Thanks!

**Comment by jfjallid** [comment]
I have now added the functionality Mkdir and MkdirAll in commit 5efd41de0253ac38d97641e21acc638cf5c1ae74 (Tag v0.3.5).
After establishing a connection (conn), you can create a directory with `conn.MkdirAll("share", "dir1/dir2/dir3")`.
