### ISSUE TITLE
[Feature Request] NTLM Info

### ISSUE THREAD

**Issue by XiaoliChan** [jfjallid/go-smb#6]
It's a good idea to get NTLM info when doing enumeration
![image](https://github.com/jfjallid/go-smb/assets/30458572/a4162c60-1831-4c81-9819-776fffabf2ba)

I think it can do this like impacket, for example
```
session.getDNSDomainName()
```

Reference:
- https://github.com/ILightThings/smb/tree/master

**Comment by jfjallid** [comment]
Thanks for the idea, I'll try to implement something similar.

**Comment by XiaoliChan** [comment]
I think these errors should be processed

In this screenshot, `0xC0000224` == `user is required to change password at next logon`
![image](https://github.com/jfjallid/go-smb/assets/30458572/094b3c3a-df34-4e45-b843-3bbcb53b74e8)

Reference:
- https://github.com/jfjallid/go-smb/blob/main/smb/session.go#L465
- https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventID=4625

**Comment by XiaoliChan** [comment]
Sweet, just test with `session.GetTargetInfo()` function, that was awesome!

**Comment by XiaoliChan** [comment]
For the error exclude "Login failed", it had a nice work now

![image](https://github.com/jfjallid/go-smb/assets/30458572/7244a9a8-42ec-4177-8887-c78e7298dcac)
